#!/bin/bash
# test_rbac_curl.sh — Test graph-based RBAC with curl commands

API_URL="http://localhost:8000"

echo "========================================================"
echo "RBAC CURL TEST COMMANDS"
echo "========================================================"
echo ""
echo "Start the API server first:"
echo "  ./venv/bin/python -m src.api"
echo ""
echo "========================================================"

# TEST 1: Admin accessing structured data
echo ""
echo "[TEST 1] Admin accessing structured data"
echo "Command:"
echo "curl -X POST $API_URL/query \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"question\": \"Which products are most frequently bought?\","
echo "    \"role\": \"admin\","
echo "    \"user_id\": \"admin_001\","
echo "    \"department\": \"IT\""
echo "  }'"
echo ""
echo "Expected: ✓ Query executes, returns results"
echo "---"

# TEST 2: Regular office accessing structured data
echo ""
echo "[TEST 2] Regular office accessing structured data"
echo "Command:"
echo "curl -X POST $API_URL/query \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"question\": \"What are the top-selling products?\","
echo "    \"role\": \"regular_office\","
echo "    \"user_id\": \"regular_001\","
echo "    \"department\": \"Sales\""
echo "  }'"
echo ""
echo "Expected: ✓ Query executes (regular_office can query 'structured')"
echo "---"

# TEST 3: Regular office trying to access document graph (should be denied)
echo ""
echo "[TEST 3] Regular office accessing Agentic Graph RAG (should be DENIED)"
echo "Command:"
echo "curl -X POST $API_URL/query \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"question\": \"What is our compliance status?\","
echo "    \"role\": \"regular_office\","
echo "    \"user_id\": \"regular_001\","
echo "    \"department\": \"Sales\""
echo "  }'"
echo ""
echo "Expected: ✗ Access denied (regular_office cannot query 'esg')"
echo "---"

# TEST 4: Compliance officer accessing document graph
echo ""
echo "[TEST 4] Compliance officer accessing Agentic Graph RAG"
echo "Command:"
echo "curl -X POST $API_URL/query \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"question\": \"Show compliance data for Q2 2024\","
echo "    \"role\": \"compliance_officer\","
echo "    \"user_id\": \"compliance_001\","
echo "    \"department\": \"Legal\""
echo "  }'"
echo ""
echo "Expected: ✓ Query executes (compliance_officer can query 'esg')"
echo "---"

# TEST 5: Public user accessing public data
echo ""
echo "[TEST 5] Public user accessing data"
echo "Command:"
echo "curl -X POST $API_URL/query \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"question\": \"What are the product categories?\","
echo "    \"role\": \"public\","
echo "    \"user_id\": \"public_001\","
echo "    \"department\": \"External\""
echo "  }'"
echo ""
echo "Expected: Limited access (public role has restricted permissions)"
echo "---"

echo ""
echo "========================================================"
echo "PASTE THESE COMMANDS IN A NEW TERMINAL WHILE API IS RUNNING"
echo "========================================================"
